### ISSUE TITLE
Auto trigger infinity scroll when scrolling to bottom view

### ISSUE THREAD

**Issue by kieuquangloc** [LawrenceHan/SVPullToRefresh#20]
Hi @LawrenceHan , I'm trying to auto triggerInfiniteScrolling when scrolling to bottom view, do you have any suggestion? currently we have to pull up to manually trigger it

![pull](https://user-images.githubusercontent.com/8148640/45464611-a12f8680-b73b-11e8-8a9e-368875cedc7b.gif)

**Comment by LawrenceHan** [comment]
```objc
- (void)scrollViewDidScroll:(UIScrollView *)scrollView {
    CGFloat magic = 600 * 2.0f; // feel free to change it to suit your need
    if (scrollView == _yourScrollView) {
        if (scrollView.contentSize.height > FLT_EPSILON) {
            if (!_isLoadingFromBottom && scrollView.contentOffset.y < (magic)) {
                // trigger it here
            }
        }
    }
}
```

**Comment by LawrenceHan** [comment]
@kieuquangloc147 Is it clear?

**Comment by kieuquangloc** [comment]
@LawrenceHan thank you for your suggestion, I know we can handle it in scrollViewDidScroll function and we have to write some conditions.

The reason is that I used to samvermette before I found out your fork, I wonder how samvermette did it in his origin project (samvermette/SVPullToRefresh), it looks like this:
![pull origin](https://user-images.githubusercontent.com/8148640/45467539-5ec17600-b74a-11e8-8681-168c61485c9c.gif)
This leads to change user experiences so I want to find out why it happened

If I can not find out any other resolution, I will use your suggestion 👍 thank you once again
